=== france193/DP2_Assignment_1a-b/dtd/nffgInfo.dtd
<!-- DTD definition for Network services -->

        <!-- This DTD file was developed by Francesco Longo for the Assignment 1
             of the course Distributed Programming II in Politechnic University of Turin. -->

        <!-- NETWORK_SERVICES -->
        <!ELEMENT NETWORK_SERVICES (NFFG*)>

        <!-- NFFG -->
        <!ELEMENT NFFG (NODE*,LINK*,POLICY*)>
        <!ATTLIST NFFG nffg_name_id ID #REQUIRED
                last_update_time CDATA #REQUIRED>

        <!-- NODE -->
        <!ELEMENT NODE EMPTY>
        <!ATTLIST NODE node_name_id ID #REQUIRED
                functional_type (firewall|dpi|nat|anti-spam|web-cache|vpn-gateway|web-server|web-client|mail-server|mail-client) "web-client">

        <!-- LINK -->
        <!ELEMENT LINK EMPTY>
        <!ATTLIST LINK link_name_id ID #REQUIRED
                source_node IDREF #REQUIRED
                destination_node IDREF #REQUIRED>

        <!-- POLICY -->
        <!ELEMENT POLICY (VERIFICATION_RESULT+, TRAVERSAL_REQUESTED_NODE*)>
        <!ATTLIST POLICY policy_name_id ID #REQUIRED
                referring_nffg IDREF #REQUIRED
                policy_kind (traversal|reachability) "reachability"
                source_node IDREF #REQUIRED
                destination_node IDREF #REQUIRED>

        <!-- VERIFICATION_RESULT -->
        <!ELEMENT VERIFICATION_RESULT EMPTY>
        <!ATTLIST VERIFICATION_RESULT policy_name_id IDREF #REQUIRED
                result (positive|negative) "negative"
                last_update_time CDATA #IMPLIED
                message CDATA #IMPLIED>

        <!-- TRAVERSAL_REQUESTED_NODE -->
        <!ELEMENT TRAVERSAL_REQUESTED_NODE EMPTY>
        <!ATTLIST TRAVERSAL_REQUESTED_NODE functional_type (firewall|dpi|nat|anti-spam|web-cache|vpn-gateway|web-server|web-client|mail-server|mail-client) "web-client">

=== france193/DP2_Assignment_1a-b/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- syntax for external dtd -->
<!DOCTYPE NETWORK_SERVICES SYSTEM "nffgInfo.dtd">
<!-- network_services -->
<NETWORK_SERVICES>
    <!-- one nffg -->
    <NFFG nffg_name_id="service_1"
          last_update_time="2016-11-09T17:17:30+01:00">
        <!-- list of nodes -->
        <NODE node_name_id="node_1" functional_type="web-client"/>
        <NODE node_name_id="node_2" functional_type="firewall"/>
        <NODE node_name_id="node_3" functional_type="nat"/>
        <NODE node_name_id="node_4" functional_type="firewall"/>
        <NODE node_name_id="node_5" functional_type="web-server"/>
        <!-- list of all CONNECTIONS between nodes for this nffg -->
        <LINK link_name_id="a" source_node="node_1" destination_node="node_2"/>
        <LINK link_name_id="b" source_node="node_2" destination_node="node_3"/>
        <LINK link_name_id="c" source_node="node_3" destination_node="node_4"/>
        <LINK link_name_id="d" source_node="node_4" destination_node="node_5"/>
    </NFFG>
    <!-- list of all POLICIES for this nffg -->
    <POLICY policy_name_id="policy_1"
            referring_nffg="service_1"
            policy_kind="reachability"
            verification_result="positive"
            source_node="node_1"
            destination_node="node_5"
            last_update_time="2016-11-09T17:18:57+01:00"/>
    <POLICY policy_name_id="policy_2"
            referring_nffg="service_1"
            policy_kind="traversal"
            verification_result="positive"
            source_node="node_1"
            destination_node="node_5"
            last_update_time="2016-11-09T17:19:27+01:00">
        <TRAVERSAL_REQUESTED_NODE functional_type="firewall"/>
    </POLICY>
    <POLICY policy_name_id="policy_3"
            referring_nffg="service_1"
            policy_kind="reachability"
            verification_result="positive"
            source_node="node_5"
            destination_node="node_1"
            last_update_time="2016-11-09T17:25:50+01:00"/>
</NETWORK_SERVICES>
